#!/usr/bin/expect -f
#
# sndFtp
#
# Author: Felix Montes
#   Date: 20 Oct 97
#
# Abstract:
#   Expect script to send files to the DB server
#   Usage:
#     sndFtp <host> <localUsername> <remoteUsername> <remotePassword>
#                <fileToSend> <localDir> <remoteFileName> <remoteDir>
#   Example:
#     sndFtp 200.34.127.110 fmontes isns mypass mxnida_cpu /u/adm/logs/tmp/mxnida.txt /CPU
#
# Revision History:
#   20 Oct 97 - Felix Montes <fmontes@dti.com.mx>
#     Initial
#

set first_time 1
set timeout 200000

if $argc>0 {
        ######################
        # Save the arguments #
        ######################
        set hostname [lindex $argv 0]
        set lusername [lindex $argv 1]
        set rusername [lindex $argv 2]
        set password [lindex $argv 3]
        set ofilename [lindex $argv 4]
        set path [lindex $argv 5]
        set rfilename [lindex $argv 6]
        set rpath [lindex $argv 7]

        ########################
        # Define the filenames #
        ########################
        set hh [exec date +%H]
        set mm [exec date +%M]
        set ss [exec date +%S]
	set log /home/sittel/logs/ftp
        set filename $ofilename
        set failfile $log/$filename.fail
        set logfile  $log/$filename.log
        set donefile $log/$filename.done

        ###############################
        # Rename the original file    #
        ###############################

#        exec mv $path/$ofilename $path/$filename

        ########################
        # Create a session log #
        ########################
        log_file -a $logfile

        ###################
        # Turn off stdout #
        ###################
        log_user 0

        ############################
        # Send a message to syslog #
        ############################
        spawn logger "sndFtp2 - sending $filename\n"

        ###############################
        # Start session with ftp host #
        ###############################
        spawn sftp $hostname

        ################################
        # Supply the username/password #
        ################################
        set timeout 60
        expect "sittel@148.243.159.248's password:" 
#{
#        } timeout {
#          expect "ftp>"
#          send "!logger sndFtp2: Timeout during connect to remote host\n"
#          expect "ftp>"
#          send "!touch $failfile\n"
#          expect "ftp>"
#          send "quit\r"
#          exit
#        }
#        send "$rusername\r"
#        expect "Password:" {
#        } timeout {
#          expect "ftp>"
#          send "!logger sndFtp2: Timeout during login to remote host\n"
#          expect "ftp>"
#          send "!touch $failfile\n"
#          expect "ftp>"
#          send "quit\r"
#          exit
#        }
        send $password
        send "\r"
        expect "sftp>" 
#{
#          expect "ftp>"
#          send "!logger sndFtp2: Failed to login for $rusername\n"
#          expect "ftp>"
#          send "!touch $failfile\n"
#          expect "ftp>"
#          send "quit\r"
#          exit
#        } timeout {
#          expect "ftp>"
#          send "!logger sndFtp2: Timeout during login to remote host\n"
#          expect "ftp>"
#          send "!touch $failfile\n"
#          expect "ftp>"
#          send "quit\r"
#          exit
#        } -re "230.*ftp>.*"

        #################
        # Send the file #
        #################
        set timeout 200000
        send "lcd $path\r"
        expect "sftp>"
#       send "site pri=5 sec=5 cy\r"
#       expect "200*ftp*>"
#        send "site rec=f lr=2083 blocksi=2083\r"
#        expect "200*ftp>*"
#        send "binary\r"
#        expect "ftp>"
        send "cd $rpath\r"
        expect "sftp>"
        send "put $filename \"$rfilename\"\r"
        expect "sftp>" 
#{
#            send "!touch $donefile\n"
#            expect "*ftp>*"
#            send "!logger sndFtp2: Finished sending $filename\n"
#            expect "ftp>"
#            send "quit\r"
#            expect "221 *"
#            exit
#        } timeout {
#          send "!logger sndFtp2: Timeout during sending of $filename\n"
#          expect "ftp>"
#          send "quit\r"
#          exit
#        } -re "ftp>"
#        send "!logger sndFtp2: Failed to send file $filename\n"
#        expect "ftp>"
#        send "!touch $failfile\n"
#        expect "ftp>"
        send "quit\r"
        exit
#}
log_user 0
spawn logger "sndFtp2 - No arguments\n"
expect eof
